plugins:
  landing_contact_email:
    default: 'hello@cocreation.world'
  landing_authorized_extensions:
    default: "jpg|jpeg|png|woff|woff2|svg|eot|ttf|otf|gif|js|json"
    type: list
    list_type: compact
  landing_redirect_to_homepages:
    default: false
    type: boolean
  landing_redirect_to_homepages_root_path:
    default: '/home-pages/sp'
